# Generated by Django 4.1.7 on 2023-09-30 22:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '0001_initial'),
        ('Profiles', '0001_initial'),
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCenter',
            fields=[
                ('learning_center_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('phone', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(regex='((\\+66|0)(\\d{1,2}\\-?\\d{3}\\-?\\d{3,4}))|((\\+๖๖|๐)([๐-๙]{1,2}\\-?[๐-๙]{3}\\-?[๐-๙]{3,4}))')])),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('popularity', models.FloatField(default=0, max_length=15)),
                ('rating', models.FloatField(default=0, max_length=15)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('approve', 'approve'), ('reject', 'reject')], default='waiting', editable=False, max_length=20)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.locations')),
            ],
            options={
                'permissions': [('learning_center_admin', 'can approve or reject the learning center, can view the waiting and reject learning center')],
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(default='', max_length=255)),
                ('image', models.ForeignKey(default=uuid.UUID('9a4b5d5d-01bd-493c-a143-2f8305dd2b35'), on_delete=django.db.models.deletion.SET_DEFAULT, to='Images.images')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.learningcenter')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsTaught',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.learningcenter')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.learningcenter')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('level_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('level_name', models.CharField(max_length=255)),
                ('image', models.ForeignKey(default=uuid.UUID('9a4b5d5d-01bd-493c-a143-2f8305dd2b35'), on_delete=django.db.models.deletion.SET_DEFAULT, to='Images.images')),
            ],
        ),
        migrations.CreateModel(
            name='LearningCenterLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.learningcenter')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.levels')),
            ],
        ),
        migrations.CreateModel(
            name='LearningCenterInteriors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(default=uuid.UUID('9a4b5d5d-01bd-493c-a143-2f8305dd2b35'), on_delete=django.db.models.deletion.CASCADE, to='Images.images')),
                ('learning_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.learningcenter')),
            ],
        ),
    ]
