# Generated by Django 4.1.7 on 2023-09-17 09:07

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcenter',
            name='address',
        ),
        migrations.RemoveField(
            model_name='learningcenter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='learningcenter',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='country',
            field=models.CharField(default='Thailand', max_length=30),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='house_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='latitude',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='longtitude',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='phone',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(regex='((\\+66|0)(\\d{1,2}\\-?\\d{3}\\-?\\d{3,4}))|((\\+๖๖|๐)([๐-๙]{1,2}\\-?[๐-๙]{3}\\-?[๐-๙]{3,4}))')]),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='province',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='section',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='street',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='sub_district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='subjects_taught',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
