# Generated by Django 4.1.7 on 2023-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCenter', '0002_remove_learningcenter_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcenter',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('approve', 'approve'), ('reject', 'reject')], default='waiting', editable=False, max_length=20),
        ),
    ]
