# Generated by Django 4.1.7 on 2023-09-21 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCenter', '0003_learningcenter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutors', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='house_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='latitude',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='longtitude',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='((\\+66|0)(\\d{1,2}\\-?\\d{3}\\-?\\d{3,4}))|((\\+๖๖|๐)([๐-๙]{1,2}\\-?[๐-๙]{3}\\-?[๐-๙]{3,4}))')]),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='province',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('approve', 'approve'), ('reject', 'reject')], default='waiting', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='street',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='sub_district',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='student_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.studentlist'),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='tutor_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.tutorlist'),
        ),
    ]
