# Generated by Django 4.1.7 on 2023-09-21 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCenter', '0004_studentlist_tutorlist_alter_learningcenter_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='learningcenter',
            name='student_list',
        ),
        migrations.RemoveField(
            model_name='learningcenter',
            name='tutor_list',
        ),
        migrations.DeleteModel(
            name='StudentList',
        ),
        migrations.AddField(
            model_name='student',
            name='learning_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.learningcenter'),
        ),
    ]
