# Generated by Django 4.1.7 on 2023-09-22 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCenter', '0005_student_remove_learningcenter_student_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('description', models.TextField()),
                ('learning_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.learningcenter')),
            ],
        ),
        migrations.DeleteModel(
            name='TutorList',
        ),
    ]
